name: tut-test

on:
  push:
    paths-ignore:
    - docs/**
    - LICENSE
    - CONTRIBUTING.md
    - CODE_OF_CONDUCT.md
    - AUTHORS
  pull_request:
    paths-ignore:
    - docs/**
    - LICENSE
    - CONTRIBUTING.md
    - CODE_OF_CONDUCT.md
    - AUTHORS
  workflow_dispatch:
    paths-ignore:
    - docs/**
    - LICENSE
    - CONTRIBUTING.md
    - CODE_OF_CONDUCT.md
    - AUTHORS
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - name: Fetch toolchain
        run: |
          wget -O- https://static.dev.sifive.com/dev-tools/riscv64-unknown-elf-gcc-8.3.0-2020.04.1-x86_64-linux-ubuntu14.tar.gz | sudo tar -xzC /opt
          echo "/opt/riscv64-unknown-elf-gcc-8.3.0-2020.04.1-x86_64-linux-ubuntu14/bin" >> $GITHUB_PATH

      - name: Setup repository
        uses: actions/checkout@v2

      - name: Setup Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'

      - name: Install prerequisites
        run: sudo apt update && sudo apt install wget openocd yosys expect ccache verilator libevent-dev libjson-c-dev libusb-1.0-0-dev libftdi1-dev

      - name: check usr bin
        run:  ls -lstr /usr/bin/

      - name: Install tuttest
        run:  sudo wget https://github.com/antmicro/tuttest/releases/download/v0.2-beta/tuttest -O /usr/bin/tuttest

      - name: check tuttest 1
        run:  ls -lstr /usr/bin/tuttest

      - name: chmod tuttest 
        run:  sudo chmod a+rx /usr/bin/tuttest

      - name: check tuttest 2
        run:  ls -lstr /usr/bin/tuttest

      - name: Check the README
        run: bash .github/scripts/tuttest-readme.sh
